### ISSUE TITLE
[Análise] - Definição de Tecnologias Utilizadas no Desenvolvimento.

### ISSUE THREAD

**Issue by lpaulovale** [es20231/eqp4#1]
**Tecnologias Escolhidas:**
Back-end: NodeJS
Front-end: VueJS
Banco de Dados: SQLite
Modelo de Autenticação: Token
Design: Figma
IDE: Visual Studio Code

**Comment by pumba-dev** [comment]
Tecnologias
Back-end: NodeJS
Front-end: VueJS
Banco de Dados: SQLite
