### ISSUE TITLE
[Análise] - Definição de Ideias e Modelagem Inicial

### ISSUE THREAD

**Issue by lpaulovale** [es20231/eqp4#2]
- Requisitos Funcionais.
- Requisitos Não Funcionais.
- Design de Baixa Fidelidade.
- Modelo Entidade Relacionamento Inicial.

**Comment by pumba-dev** [comment]
**Reunião Agendada**
Data: 24/05/2023 às 12:00 
Local: Universidade Federal do Piauí - UFPI

**Comment by pumba-dev** [comment]
**Documentos Gerados**
https://drive.google.com/drive/folders/1MaWiMoZ7qxw56tSlUSbUPl0I1Qp8dFSC?usp=drive_link
